#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

exec twistd --nodaemon --pidfile plugin-service.pid \
  cyclone --app minion.plugin_service.web.Application --port=8181 --listen=127.0.0.1

