#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

exec twistd --nodaemon --pidfile task-engine.pid \
  cyclone --app minion.task_engine.web.Application --port=8282 --listen=0.0.0.0
